### ISSUE TITLE
Discord is very slow and sluggish after a while

### ISSUE THREAD

**Issue by odesb** [flathub/com.discordapp.Discord#135] opened 2021-01-17 17:21 UTC
Problem: Discord gets unusable after medium-long voice chat sessions with multiple users (memory leak?). It doesn't do that with the Fedora-packaged Discord or the browser-based version. I use Fedora 33 Workstation.

Here is the log:
https://gist.github.com/xisbroken/ffed60501c54ef52a3ffd2ba6fc6f354

**Comment by lionirdeadman** [comment] 2021-01-17 20:52
Can you verify that it's a memory leak by looking at memory usage over time?

**Comment by kernitus** [comment] 2021-01-18 01:00
I believe I have the same issue, a restart of the app is usually required to make the interface responsive again. I don't think it's a memory leak because I don't see the RAM usage going up significantly over time. How would I identify what the issue could be? One thing I noticed is that video (both webcams and streams) seem to accelerate the process of the UI becoming sluggish, up to the point where it takes ~60s to respond to a click.

**Comment by xisbroken** [comment] 2021-01-18 05:03
> Can you verify that it's a memory leak by looking at memory usage over time?

No, I just checked, the memory usage does not increase significantly.

**Comment by wpehrc** [comment] 2021-01-19 18:56
I can confirm that a memory leak does indeed exist but I do not know the origin, nor am I able to reproduce it at this moment. Discord is not supposed to use 1.5GB of memory, but on numerous occasions it did.

**Comment by vilhelmprytz** [comment] 2021-01-23 23:09
Not too sure if I can help anything, but I have the exact same issue. I'd be happy to provide any debug information as well if needed!

**Comment by alvarlagerlof** [comment] 2021-01-23 23:16
I suffer from this also, I'm almost at the point of installing it from some other place, unsandboxed. Don't want to do that. Also happy to provide logs.

**Comment by Pinjontall94** [comment] 2021-02-14 01:25
Also suffer from this, also will provide logs if needed! Seems worse with voice chats (normally I leave discord running without issue). Idk if that's because of the bandwidth increase or if it's specific to voice, though.

**Comment by Binero** [comment] 2021-03-30 16:02
Quick search online taught me this is likely because of an outdated version of electron. Many people experience a similar issue on non-flatpak distributed versions of Discord as well and are able to resolve their issue by updating the electron version. 

Good summary I found: https://www.reddit.com/r/archlinux/comments/kcbjcu/discord_becomes_laggy_during_long_voice_calls/gfseckg

**Comment by guihkx** [comment] 2024-10-02 17:37
This issue is almost 4 years old at this point and it hasn't received any comments recently, so it's possible that slowness and sluggishness issues have been fixed with updates to Discord/Electron.

However, if this is still a problem for you, just comment here and I'll reopen the issue.

**Closed by guihkx** 2024-10-02 17:37 UTC
Labels: bug, help wanted
