### ISSUE TITLE
"Well, this is awkward" Loop

### ISSUE THREAD

**Issue by kurobeats** [flathub/com.discordapp.Discord#72] opened 2019-06-16 05:10 UTC
Can't do anything after opening, it just loops the error screen with the "reload" button:

![Screenshot from 2019-06-16 13-08-52](https://user-images.githubusercontent.com/4091936/59559364-27b12580-9038-11e9-988a-a5cf5388ca7f.png)

```
$ com.discordapp.Discord 
Gtk-Message: 13:03:35.374: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:03:35.374: Failed to load module "canberra-gtk-module"
Discord 0.0.9
Starting app.
Starting updater.
[Modules] Modules initializing
[Modules] Distribution: remote
[Modules] Host updates: enabled
[Modules] Module updates: enabled
[Modules] Module install path: /var/home/USER/.var/app/com.discordapp.Discord/config/discord/0.0.9/modules
[Modules] Module installed file path: /var/home/USER/.var/app/com.discordapp.Discord/config/discord/0.0.9/modules/installed.json
[Modules] Module download path: /var/home/USER/.var/app/com.discordapp.Discord/config/discord/0.0.9/modules/pending
[Modules] No updates to install
[Modules] Checking for host updates.
[Modules] Host is up to date.
[Modules] Checking for module updates at https://discordapp.com/api/modules/stable/versions.json
[Modules] No module updates available.
Feature redeclared; is this a duplicate flag?  voice_panning
Feature redeclared; is this a duplicate flag?  voice_multiple_connections
Feature redeclared; is this a duplicate flag?  media_devices
Feature redeclared; is this a duplicate flag?  media_video
Feature redeclared; is this a duplicate flag?  debug_logging
Feature redeclared; is this a duplicate flag?  set_audio_device_by_id
Feature redeclared; is this a duplicate flag?  loopback
```

**Comment by AlexKF98** [comment] 2019-06-22 20:07
Duplicate of #71

**Comment by ricvelozo** [comment] 2019-06-24 19:41
See https://github.com/flathub/com.discordapp.Discord/issues/53#issuecomment-496020265

**Comment by iglosiggio** [comment] 2019-10-04 03:55
Hi (im going to repost this in all the duplicated issues). After digging a while seems caused by [this](https://bugs.chromium.org/p/chromium/issues/detail?id=364374) bug in chromium. Maybe updating the electron version will fix it?

**Comment by Fuseteam** [comment] 2020-04-14 22:23
Is this still an issue?

**Comment by LapysDev** [comment] 2020-07-29 07:37
Apparently so

**Comment by Fuseteam** [comment] 2020-07-29 18:06
i do not have this issue

**Comment by TingPing** [comment] 2020-07-29 18:45
There is likely nothing this package can do about it unless this is somehow tracked down to a library thats a problem.

Deleting `~/.var/app/com.discordapp.Discord/` often fixes issues.

**Closed by TingPing** 2020-07-29 18:45 UTC

**Comment by Fuseteam** [comment] 2020-07-30 14:50
is possible for this package to regenerate `~/.var/app/com.discordapp.Discord`?
