### ISSUE TITLE
Discord cant find any games

### ISSUE THREAD

**Issue by Tids** [flathub/com.discordapp.Discord#13] opened 2017-12-29 14:20 UTC
Discord is able to look what you're playing and show this as status message.
This works with the "Native" version, but not with that flatpak version of discord.

in Settings > Games you can add games, but the only thing that discord finds is "bwrap", wich is not a game but part of flatpak.

I think thats because of the sandbox. No idea how to handle this.

**Comment by TingPing** [comment] 2017-12-29 14:24
Duplicate of #11

**Closed by TingPing** 2017-12-29 14:24 UTC
