### ISSUE TITLE
Discord not sharing apps screen and share black screen

### ISSUE THREAD

**Issue by leoelmago** [flathub/com.discordapp.Discord#159] opened 2021-07-06 22:54 UTC
Hello

OS: Debian GNU/Linux 11 (bullseye)
Discord: com.discordapp.Discord 0.0.15 stable

I have two issues:
- Can't share any app screen. Only can share firefox app.
![app_screen](https://user-images.githubusercontent.com/62481331/124675809-c6b15000-de93-11eb-85fc-15c9c06684a3.png)

- Black screen when I try share my desktop screens
![black_screen](https://user-images.githubusercontent.com/62481331/124675811-c749e680-de93-11eb-8de4-15d2cd161be7.png)

Thanks

**Comment by lionirdeadman** [comment] 2021-07-07 04:21
Hi! This is not specific to the Flatpak package. This is because Discord doesn't support Wayland screen sharing.

This is also a duplicate of https://github.com/flathub/com.discordapp.Discord/issues/89

**Closed by lionirdeadman** 2021-07-07 04:21 UTC
