### ISSUE TITLE
So flatpak discord will never be able to detect running games? or is something being worked on

### ISSUE THREAD

**Issue by Ecabott** [flathub/com.discordapp.Discord#116] opened 2020-10-26 21:33 UTC

**Comment by lionirdeadman** [comment] 2020-10-26 23:29
I believe this should still work : https://github.com/flathub/com.discordapp.Discord/wiki/Rich-Precense-(discord-rpc)

Closing as duplicate of #115 at least

**Closed by lionirdeadman** 2020-10-26 23:29 UTC
