### ISSUE TITLE
Gpu encoding?

### ISSUE THREAD

**Issue by polluxau** [flathub/com.discordapp.Discord#359] opened 2024-01-05 18:39 UTC
Been using linux for over a year now and cant screen share my games without my fps getting cut in half.

Like overwatch 2 200fps, start screen sharing, 80fps.. 

Does anybody know of any plans if discord will bring gpu encoding to screen sharing for linux? Like ffmpeg vaapi? Or nvenc from nvidia?

**Comment by TingPing** [comment] 2024-01-07 17:55
This is a question for Discord not the package.

I'm pretty sure Pipewire can do zero-copy screen sharing but I have no idea the implementation details inside of Electron or how Discord does it.

**Comment by guihkx** [comment] 2024-10-02 18:48
Closing as duplicate of https://github.com/flathub/com.discordapp.Discord/issues/114.

**Closed by guihkx** 2024-10-02 18:48 UTC
Labels: question, upstream
