### ISSUE TITLE
discord crashes after few hours in voice

### ISSUE THREAD

**Issue by fishxz** [flathub/com.discordapp.Discord#65] opened 2019-04-25 22:24 UTC
```
Process 2665 (discord) of user 1000 dumped core.

Stack trace of thread 4:
#0  0x00007f2402db02b5 n/a (/app/lib/libappindicator3.so.1.0.0)
```

im on fedora 30 silverblue

**Comment by TingPing** [comment] 2019-04-26 00:40
Duplicate of #30

**Closed by TingPing** 2019-04-26 00:40 UTC
