### ISSUE TITLE
Options from system tray icon are not working

### ISSUE THREAD

**Issue by glaubersm** [flathub/com.discordapp.Discord#20] opened 2018-01-30 17:56 UTC
Options below from system tray icon are not working.
Gnome 3.26.2 and KDE Plasma 5.12 beta are affected.

voice/video settings - nothing happens
check for updates - nothing happens
quit discord - a new instance is opened (???)

**Comment by TingPing** [comment] 2018-02-01 17:32
I cannot reproduce on GNOME-Shell, everything works.

**Comment by glaubersm** [comment] 2018-02-01 19:15
Weird. I can reproduce on Arch Linux and neon dev unstable when Discord is disconnected.

**Comment by ankworld** [comment] 2018-03-18 09:47
I can't quit discord with "Quit Discord" from system tray icon too. It will open discord window. Setting and check for update work for me.

**Comment by glaubersm** [comment] 2018-03-18 11:37
"voice/video settings" and "check for updates" only work when Discord is connected despite these options are enabled when Discord is disconnected.
"quit Discord" opens another and empty window as you can see in the following screenshot.

![captura de tela de 2018-03-18 08-34-03](https://user-images.githubusercontent.com/15967631/37565387-53399fa6-2a87-11e8-953d-70d53e43a316.png)

**Comment by TingPing** [comment] 2018-03-18 11:40
@glaubersm Do you use topicons or statusnotifier extension on gnome?

**Comment by glaubersm** [comment] 2018-03-18 11:45
Yes. However the problems described here also occur in KDE Plasma.

**Comment by TingPing** [comment] 2018-03-18 11:48
That wasn't really a yes/no question :P. Anyway I use statusnotifier on GNOME which *should* behave identical to Plasma. And with that I don't think there is anything that can be done here.

**Comment by glaubersm** [comment] 2018-03-18 11:53
I just replaced topicons extension with (K)StatusNotifierItem/AppIndicator and did no difference.

**Comment by glaubersm** [comment] 2018-03-18 12:20
I just installed Discord from AUR on Arch Linux.
Now "Quit Discord" works as expected.

**Comment by jython234** [comment] 2018-03-20 01:47
Can reproduce on Manjaro with Gnome. Quit discord button opens a new discord instance which means now there's two windows of discord and it just is impossible to close. Sometimes I'm lucky and it closes, but lately it just stopped working. I've switched to using the Discord snap, which works perfectly.

**Comment by glaubersm** [comment] 2018-03-20 02:54
discord installed via snap package also is not closed correctly on my system (neon dev unstable, KDE Plasma). Exactly the same problem. lol

**Comment by jython234** [comment] 2018-03-20 02:59
That's weird, my snap works completely fine. Did you install using "snap
install discord"?

**Comment by glaubersm** [comment] 2018-03-20 03:03
No. I installed it via Discover.

**Comment by glaubersm** [comment] 2018-03-21 00:29
Humm, I did more tests on VirtualBox.
Discord installed via official repositories on Opensuse Tumbleweed + KDE Plasma: same problem.
Discord installed via flatpak/flathub on Void + Cinnamon: same problem.
Discord installed via DEB package on neon dev unstable + KDE Plasma: same problem.

I will report to Discord devs.

**Comment by Cxpher** [comment] 2018-04-12 02:37
Same issues exist with Discord installed via flathub on Arch Linux with GNOME.

**Comment by glaubersm** [comment] 2018-04-12 03:31
I reported this problem to upstream a few weeks ago, I can't reproduce on KDE Plasma anymore.

I just tested Discord installed from flathub on Arch running Gnome 3.28.1 + TopIcons shell extension and "Quit Discord" is still not working. Other two options work correctly.
Discord installed via Snap or archlinuxfr repository has no problem.

**Comment by eiglow** [comment] 2020-10-24 06:10
The options I get are:

- "Open Discord", which seems to work fine, bringing the Discord window into focus
- "Check for Updates", which doesn't do anything obvious to me. I'm assuming Discord is already up to date or something.
- "Acknowledgements", which seems to work fine, opening up [this](https://discord.com/acknowledgements) in a new web browser tab
- "Quit Discord", which seems to quit Discord, as expected.

So I think this issue is fixed? I am running this flatpak on Fedora 32 in a KDE Plasma X11 session.

**Comment by Fuseteam** [comment] 2020-10-24 15:26
2 years old o.O

**Comment by lionirdeadman** [comment] 2020-12-20 22:01
Based on the message from eiglow, seems this can be closed indeed. Feel free to reopen if needed.

**Comment by bitterseeds** [comment] 2021-06-19 01:57
Issue might be closed but it still behaves this way on KDE Plasma 5.21.5. I can't close it from the systray.

**Comment by lionirdeadman** [comment] 2021-06-19 05:04
Strange. As you can see above, someone using KDE had it working so there must've been a regression at some point.

**Comment by bitterseeds** [comment] 2021-06-19 05:43
> Strange. As you can see above, someone using KDE had it working so there must've been a regression at some point.

I figured out the issue. It's probably been the issue all along. If you edit the configs for the KDE systray you'll see it says "show when relevant" and if this is chosen (it is the default) ... then you can not click the bottom two options of the four. If you choose "Always Shown" then it works perfectly fine. 

I don't know if this is an issue with KDE or the Discord app but it was a bit to puzzle through. It caused me about 40 minutes of trying this or trying that then I figured out what Discord likes as far as the systray. :)

Just hope when someone searches for this same issue, they'll see this is the way to sort it.

**Closed** 2023-04-29 06:18 UTC
Labels: upstream
