### ISSUE TITLE
Application autostart not working

### ISSUE THREAD

**Issue by sashaoshurkov** [flathub/com.discordapp.Discord#234] opened 2022-07-22 05:31 UTC
Hello,

Discord has an option to allow the app to automatically launch. However, on Fedora 36, when using a flatpak, this option does not work, because Discord creates a .desktop file in the wrong place. Although the same Telegram from flatpak can create a .desktop file in the right place.
![image](https://user-images.githubusercontent.com/1682848/180369564-90db7ced-7aff-4384-9d5d-1d9c5916029e.png)

**Comment by TingPing** [comment] 2022-07-22 20:16
Discord has to support Flatpak by using the autostart portal. In theory we could do complicated things to try and do this for them but that would mean somebody volunteering to do that.

**Comment by TingPing** [comment] 2022-07-22 20:17
Duplicate of #21

**Closed by TingPing** 2022-07-22 20:17 UTC
Labels: upstream
