### ISSUE TITLE
Cannot share files

### ISSUE THREAD

**Issue by brittyazel** [flathub/com.discordapp.Discord#62] opened 2019-03-20 16:38 UTC
With the Discord flatpak I cannot share files. When I try to drag and drop files into the window, the Discord animation shows up that says "drag and drop", but dropping does nothing.

Also, what's worse is that if I try to manually select a file to add from the little "+" button, almost all off my folders in /home are missing. The only folders in my home folder that show are Downloads, Pictures, and Videos. I have to copy any file I want to share into one of those three folders in order for it to show in the file chooser dialog

**Comment by TingPing** [comment] 2019-03-20 19:44
Duplicate of #10

**Closed by TingPing** 2019-03-20 19:44 UTC
