### ISSUE TITLE
Pop up notifications in Gnome can't be disabled

### ISSUE THREAD

**Issue by ISpeakHue** [flathub/com.discordapp.Discord#176] opened 2021-09-22 21:35 UTC
I'm using Fedora and using the native Discord package I can disable the pop up notifications in the notifications panel in Gnome Settings. The flatpak version doesn't show Discord notification settings on the notifications panel in Gnome Settings. 
Disabling notifications in the Applications panel in Gnome Settings doesn't work, pop up notifications keep showing.

**Comment by TingPing** [comment] 2021-09-23 21:44
I would guess GNOME expects notifications to include an app-id in them, but I'm not sure about that.

Since Discord is proprietary we can't sanely modify how it behaves though.

**Comment by ISpeakHue** [comment] 2021-09-23 23:04
As I said, the native package from RPMfusion has notifications working as intended, but the flatpak version always has the pop up notifications on and it is super anoying

**Comment by ISpeakHue** [comment] 2021-10-17 16:52
> Sorry for being late. Could it be that you kept gnome-control-center open while you uninstalled the package? I believe that might result in a bug where the setting doesn't affect one but it does the other.

I tested it and no, rebooting and not opening Gnome Settings while uninstalling the native package and installing the Flatpak doesn't solve the problem, notifications still don't appear in Gnome Settings notifications pannel

**Comment by lionirdeadman** [comment] 2021-11-14 05:38
I've just re-read this and realized I made a mistake. I assumed you meant the Settings -> Applications -> Discord but instead you meant Settings -> Notifications.

I can indeed reproduce this but I have no idea why this happens..

**Comment by TheHooly** [comment] 2022-02-12 15:37
@ISpeakHue What if you revoke the permission to talk with `org.freedesktop.Notifications` ?

**Comment by notanimposter** [comment] 2023-02-13 11:45
I don't use GNOME but I have the exact same problem in Pantheon, and I can tell you what fixed it for me. The .desktop file *must* be called `discord.desktop` (as you'll find in the deb/rpm packages) in order for Discord's notifications to show up to the DE as "Discord" instead of "Other".

What I did to fix this on my own system was copy `com.discordapp.Discord.desktop` to `~/.local/share/applications`, adding `NoDisplay=true`. Then I made another copy, `discord.desktop` in the same directory, adding `X-GNOME-UsesNotifications=true`. Once the `discord.desktop` file was present, notifications began to work perfectly.

If this doesn't fix it on GNOME I can make a separate issue for Pantheon, but I bet it will.

**Comment by guihkx** [comment] 2024-10-05 12:51
Revisiting this on Ubuntu 20.04 (GNOME 3.36.8), Discord now shows up correctly in the Notifications panel:

![Screenshot from 2024-10-05 12-42-52](https://github.com/user-attachments/assets/74359b9c-cf54-420b-bb87-cc16dde75c39)

I think this was fixed by accident in ad0d21091ea71fd094b2baba6107d898950303d5, more specifically, after [patching](https://github.com/flathub/com.discordapp.Discord/blob/bac383aadc17f9f0c1ff92d5d56122d2387766a4/com.discordapp.Discord.json#L46) Discord's `app.asar`, which unpacks the `asar` file, updates the `desktopName` key in `package.json` to use `com.discordapp.Discord.desktop` instead of `discord.desktop`, and then finally repacks it into an `asar` file again.

**Closed by guihkx** 2024-10-05 12:51 UTC
Labels: bug, help wanted
