### ISSUE TITLE
Cannot paste into window

### ISSUE THREAD

**Issue by Justinzobel** [flathub/com.discordapp.Discord#412] opened 2024-06-30 02:05 UTC
Trying to log in and copied password from my password manager and pasted but nothing appears. I tried pasting in a note file and it works fine.

**Comment by guihkx** [comment] 2024-10-02 23:28
I cannot reproduce the issue here. I tested this on Plasma 6.1.5 (X11 session), by copying a random password from the KeePassXC window, and I was able to successfully paste into Discord.

Can you please share a bit more details on this? Like what is your distribution name, desktop environment and version... Are you on Wayland or X11?

**Comment by guihkx** [comment] 2024-11-04 21:32
Closing, as the reporter seems unavailable for a follow-up at this time.

Please retest this with latest Discord, and if the problem still exists, please open a new issue providing the details I asked above.

**Closed by guihkx** 2024-11-04 21:32 UTC
Labels: needs info
