### ISSUE TITLE
Hard quit (but apparently not browser crash?) in the middle of first launch for initial updates, impossible to reach main UI

### ISSUE THREAD

**Issue by ell1e** [flathub/com.discordapp.Discord#370] opened 2024-02-10 07:49 UTC
When I launch discord on this machine I get a hard quit (but apparently not browser crash?) in the middle of first launch for initial updates:

![discordbug](https://github.com/flathub/com.discordapp.Discord/assets/64124388/5a6e77ec-d992-4f6c-a576-89184263dcee)

This is where it quits, with always a little of a different progress bar position, but it never makes it to the main UI. So basically I can just watch 2-3 seconds of loading screen and that's all the app ever manages to do, turning it effectively inaccessible.

**Comment by lionirdeadman** [comment] 2024-02-10 17:29
You should be able to delete everything in `~/.var/app/com.discordapp.Discord/` and that should delete all Discord state and fix the issue most likely. Note that this will log you out.

**Comment by ell1e** [comment] 2024-02-10 17:52
I just tried your suggestion, but sadly it has the same problem.

I wasn't logged in on this device before so I would be logged out anyway!

**Comment by lionirdeadman** [comment] 2024-02-10 18:03
Hm, that is odd. Can you look at the output log to see if there's anything weird? `flatpak run com.discordapp.Discord`

**Comment by ell1e** [comment] 2024-02-10 18:09
Here is the output:
```
$ flatpak run com.discordapp.Discord
2024/02/10 19:06:55 socat[3] E "/run/user/1000/app/com.discordapp.Discord/discord-ipc-0" exists
Disabling updates already done
Discord 0.0.42
[5:0210/190656.119281:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[5:0210/190656.119352:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Starting app.
Starting updater.
2024-02-10T18:06:56.143Z [Modules] Modules initializing
2024-02-10T18:06:56.143Z [Modules] Distribution: remote
2024-02-10T18:06:56.143Z [Modules] Host updates: disabled
2024-02-10T18:06:56.144Z [Modules] Module updates: enabled
2024-02-10T18:06:56.144Z [Modules] Module install path: /home/user/.var/app/com.discordapp.Discord/config/discord/0.0.42/modules
2024-02-10T18:06:56.144Z [Modules] Module installed file path: /home/user/.var/app/com.discordapp.Discord/config/discord/0.0.42/modules/installed.json
2024-02-10T18:06:56.144Z [Modules] Module download path: /home/user/.var/app/com.discordapp.Discord/config/discord/0.0.42/modules/pending
splashScreen.initSplash(false)
blackbox: 2024-02-10T18:06:56.163Z 0 

----------------------------------------------
blackbox: 2024-02-10T18:06:56.180Z 1 Discord starting: {"releaseChannel":"stable","version":"0.0.42"}, modulepath: /home/user/.var/app/com.discordapp.Discord/config/discord/0.0.42/modules
blackbox: 2024-02-10T18:06:56.185Z 2 ✅ webContents.created web1 ""
blackbox: 2024-02-10T18:06:56.189Z 3 ✅ window.created win1 "discord"
splashScreen: SPLASH_SCREEN_READY
2024-02-10T18:06:56.365Z [Modules] No updates to install
splashScreen: no-pending-updates
2024-02-10T18:06:56.366Z [Modules] Host is up to date.
2024-02-10T18:06:56.366Z [Modules] Checking for module updates at https://discord.com/api/modules/stable/versions.json
splashScreen: checking-for-updates
splashScreen.updateSplashState checking-for-updates checking-for-updates {}
splashScreen.webContentsSend: SPLASH_UPDATE_STATE SPLASH_UPDATE_STATE [ { status: 'checking-for-updates' } ]
2024-02-10T18:06:56.377Z [Modules] Module update available: discord_erlpack@1 [installed: 0]
2024-02-10T18:06:56.377Z [Modules] Module update available: discord_spellcheck@1 [installed: 0]
2024-02-10T18:06:56.378Z [Modules] Module update available: discord_utils@1 [installed: 0]
2024-02-10T18:06:56.378Z [Modules] Module update available: discord_voice@2 [installed: 0]
splashScreen: update-check-finished true 4 false
2024-02-10T18:06:56.378Z [Modules] Fetching discord_erlpack@1 from https://discord.com/api/modules/stable/discord_erlpack/1
2024-02-10T18:06:56.378Z [Modules] Streaming discord_erlpack@1 to /home/user/.var/app/com.discordapp.Discord/config/discord/0.0.42/modules/pending/discord_erlpack-1.zip
splashScreen: downloading-module discord_erlpack 1 4
splashScreen.updateSplashState downloading-updates downloading-updates { current: 1, total: 4 }
splashScreen.webContentsSend: SPLASH_UPDATE_STATE SPLASH_UPDATE_STATE [ { status: 'downloading-updates', current: 1, total: 4 } ]
[54:0210/190656.416189:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
[54:0210/190656.417592:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
[54:0210/190656.420098:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
[54:0210/190656.420556:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
[54:0210/190656.421849:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
blackbox: 2024-02-10T18:06:56.422Z 4 ✅ webContents.did-finish-load web1
[54:0210/190656.454921:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
[54:0210/190656.621032:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
2024-02-10T18:06:57.259Z [Modules] Streaming discord_erlpack@1 to /home/user/.var/app/com.discordapp.Discord/config/discord/0.0.42/modules/pending/discord_erlpack-1.zip: 100%
splashScreen: downloading-module-progress discord_erlpack 100
splashScreen.updateSplashState downloading-updates downloading-updates { current: 1, total: 4, progress: 100 }
splashScreen.webContentsSend: SPLASH_UPDATE_STATE SPLASH_UPDATE_STATE [
  {
    status: 'downloading-updates',
    current: 1,
    total: 4,
    progress: 100
  }
]
splashScreen: downloaded-module discord_erlpack 1 4 true
2024-02-10T18:06:58.401Z [Modules] Fetching discord_spellcheck@1 from https://discord.com/api/modules/stable/discord_spellcheck/1
2024-02-10T18:06:58.401Z [Modules] Streaming discord_spellcheck@1 to /home/user/.var/app/com.discordapp.Discord/config/discord/0.0.42/modules/pending/discord_spellcheck-1.zip
splashScreen: downloading-module discord_spellcheck 2 4
splashScreen.updateSplashState downloading-updates downloading-updates { current: 2, total: 4 }
splashScreen.webContentsSend: SPLASH_UPDATE_STATE SPLASH_UPDATE_STATE [ { status: 'downloading-updates', current: 2, total: 4 } ]
2024-02-10T18:06:59.066Z [Modules] Streaming discord_spellcheck@1 to /home/user/.var/app/com.discordapp.Discord/config/discord/0.0.42/modules/pending/discord_spellcheck-1.zip: 1%
splashScreen: downloading-module-progress discord_spellcheck 1
splashScreen.updateSplashState downloading-updates downloading-updates { current: 2, total: 4, progress: 1 }
splashScreen.webContentsSend: SPLASH_UPDATE_STATE SPLASH_UPDATE_STATE [
  { status: 'downloading-updates', current: 2, total: 4, progress: 1 }
]
2024-02-10T18:06:59.147Z [Modules] Streaming discord_spellcheck@1 to /home/user/.var/app/com.discordapp.Discord/config/discord/0.0.42/modules/pending/discord_spellcheck-1.zip: 2%
splashScreen: downloading-module-progress discord_spellcheck 2
splashScreen.updateSplashState downloading-updates downloading-updates { current: 2, total: 4, progress: 2 }
splashScreen.webContentsSend: SPLASH_UPDATE_STATE SPLASH_UPDATE_STATE [
  { status: 'downloading-updates', current: 2, total: 4, progress: 2 }
]
2024-02-10T18:06:59.227Z [Modules] Streaming discord_spellcheck@1 to /home/user/.var/app/com.discordapp.Discord/config/discord/0.0.42/modules/pending/discord_spellcheck-1.zip: 3%
splashScreen: downloading-module-progress discord_spellcheck 3
splashScreen.updateSplashState downloading-updates downloading-updates { current: 2, total: 4, progress: 3 }
splashScreen.webContentsSend: SPLASH_UPDATE_STATE SPLASH_UPDATE_STATE [
  { status: 'downloading-updates', current: 2, total: 4, progress: 3 }
]
2024-02-10T18:06:59.291Z [Modules] Streaming discord_spellcheck@1 to /home/user/.var/app/com.discordapp.Discord/config/discord/0.0.42/modules/pending/discord_spellcheck-1.zip: 4%
splashScreen: downloading-module-progress discord_spellcheck 4
splashScreen.updateSplashState downloading-updates downloading-updates { current: 2, total: 4, progress: 4 }
splashScreen.webContentsSend: SPLASH_UPDATE_STATE SPLASH_UPDATE_STATE [
  { status: 'downloading-updates', current: 2, total: 4, progress: 4 }
]
2024-02-10T18:06:59.652Z [Modules] Streaming discord_spellcheck@1 to /home/user/.var/app/com.discordapp.Discord/config/discord/0.0.42/modules/pending/discord_spellcheck-1.zip: 5%
splashScreen: downloading-module-progress discord_spellcheck 5
splashScreen.updateSplashState downloading-updates downloading-updates { current: 2, total: 4, progress: 5 }
splashScreen.webContentsSend: SPLASH_UPDATE_STATE SPLASH_UPDATE_STATE [
  { status: 'downloading-updates', current: 2, total: 4, progress: 5 }
]
2024-02-10T18:07:00.688Z [Modules] Streaming discord_spellcheck@1 to /home/user/.var/app/com.discordapp.Discord/config/discord/0.0.42/modules/pending/discord_spellcheck-1.zip: 6%
splashScreen: downloading-module-progress discord_spellcheck 6
splashScreen.updateSplashState downloading-updates downloading-updates { current: 2, total: 4, progress: 6 }
splashScreen.webContentsSend: SPLASH_UPDATE_STATE SPLASH_UPDATE_STATE [
  { status: 'downloading-updates', current: 2, total: 4, progress: 6 }
]
2024-02-10T18:07:00.796Z [Modules] Streaming discord_spellcheck@1 to /home/user/.var/app/com.discordapp.Discord/config/discord/0.0.42/modules/pending/discord_spellcheck-1.zip: 7%
splashScreen: downloading-module-progress discord_spellcheck 7
splashScreen.updateSplashState downloading-updates downloading-updates { current: 2, total: 4, progress: 7 }
splashScreen.webContentsSend: SPLASH_UPDATE_STATE SPLASH_UPDATE_STATE [
  { status: 'downloading-updates', current: 2, total: 4, progress: 7 }
]
2024-02-10T18:07:01.142Z [Modules] Streaming discord_spellcheck@1 to /home/user/.var/app/com.discordapp.Discord/config/discord/0.0.42/modules/pending/discord_spellcheck-1.zip: 8%
splashScreen: downloading-module-progress discord_spellcheck 8
splashScreen.updateSplashState downloading-updates downloading-updates { current: 2, total: 4, progress: 8 }
splashScreen.webContentsSend: SPLASH_UPDATE_STATE SPLASH_UPDATE_STATE [
  { status: 'downloading-updates', current: 2, total: 4, progress: 8 }
]
2024-02-10T18:07:01.342Z [Modules] Streaming discord_spellcheck@1 to /home/user/.var/app/com.discordapp.Discord/config/discord/0.0.42/modules/pending/discord_spellcheck-1.zip: 9%
splashScreen: downloading-module-progress discord_spellcheck 9
splashScreen.updateSplashState downloading-updates downloading-updates { current: 2, total: 4, progress: 9 }
splashScreen.webContentsSend: SPLASH_UPDATE_STATE SPLASH_UPDATE_STATE [
  { status: 'downloading-updates', current: 2, total: 4, progress: 9 }
]
2024-02-10T18:07:01.947Z [Modules] Streaming discord_spellcheck@1 to /home/user/.var/app/com.discordapp.Discord/config/discord/0.0.42/modules/pending/discord_spellcheck-1.zip: 10%
splashScreen: downloading-module-progress discord_spellcheck 10
splashScreen.updateSplashState downloading-updates downloading-updates { current: 2, total: 4, progress: 10 }
splashScreen.webContentsSend: SPLASH_UPDATE_STATE SPLASH_UPDATE_STATE [
  { status: 'downloading-updates', current: 2, total: 4, progress: 10 }
]
2024-02-10T18:07:02.353Z [Modules] Streaming discord_spellcheck@1 to /home/user/.var/app/com.discordapp.Discord/config/discord/0.0.42/modules/pending/discord_spellcheck-1.zip: 11%
splashScreen: downloading-module-progress discord_spellcheck 11
splashScreen.updateSplashState downloading-updates downloading-updates { current: 2, total: 4, progress: 11 }
splashScreen.webContentsSend: SPLASH_UPDATE_STATE SPLASH_UPDATE_STATE [
  { status: 'downloading-updates', current: 2, total: 4, progress: 11 }
]
2024-02-10T18:07:02.652Z [Modules] Streaming discord_spellcheck@1 to /home/user/.var/app/com.discordapp.Discord/config/discord/0.0.42/modules/pending/discord_spellcheck-1.zip: 12%
splashScreen: downloading-module-progress discord_spellcheck 12
splashScreen.updateSplashState downloading-updates downloading-updates { current: 2, total: 4, progress: 12 }
splashScreen.webContentsSend: SPLASH_UPDATE_STATE SPLASH_UPDATE_STATE [
  { status: 'downloading-updates', current: 2, total: 4, progress: 12 }
]
2024-02-10T18:07:03.039Z [Modules] Streaming discord_spellcheck@1 to /home/user/.var/app/com.discordapp.Discord/config/discord/0.0.42/modules/pending/discord_spellcheck-1.zip: 13%
splashScreen: downloading-module-progress discord_spellcheck 13
splashScreen.updateSplashState downloading-updates downloading-updates { current: 2, total: 4, progress: 13 }
splashScreen.webContentsSend: SPLASH_UPDATE_STATE SPLASH_UPDATE_STATE [
  { status: 'downloading-updates', current: 2, total: 4, progress: 13 }
]
2024-02-10T18:07:03.500Z [Modules] Streaming discord_spellcheck@1 to /home/user/.var/app/com.discordapp.Discord/config/discord/0.0.42/modules/pending/discord_spellcheck-1.zip: 14%
splashScreen: downloading-module-progress discord_spellcheck 14
splashScreen.updateSplashState downloading-updates downloading-updates { current: 2, total: 4, progress: 14 }
splashScreen.webContentsSend: SPLASH_UPDATE_STATE SPLASH_UPDATE_STATE [
  { status: 'downloading-updates', current: 2, total: 4, progress: 14 }
]
$

```

**Comment by guihkx** [comment] 2024-10-03 02:59
```
[54:0210/190656.416189:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
```

That error indicates this is a duplicate of #307.

**Closed by guihkx** 2024-10-03 02:59 UTC
