### ISSUE TITLE
Discord 0.0.8 crashes on launch

### ISSUE THREAD

**Issue by Cxpher** [flathub/com.discordapp.Discord#53] opened 2019-01-27 03:47 UTC
Hi,

Crashes upon launch and goes into a reload loop.

Error in console is..

TypeError: Cannot read property 'format' of undefined
    at t.renderHeader (7380edb1e656997102a0.js:1)
    at t.render (7380edb1e656997102a0.js:1)
    at Qo (824772519e8b9ac65e01.js:117)
    at Xo (824772519e8b9ac65e01.js:117)
    at ti (824772519e8b9ac65e01.js:117)
    at Li (824772519e8b9ac65e01.js:117)
    at Mi (824772519e8b9ac65e01.js:117)
    at fa (824772519e8b9ac65e01.js:117)
    at ca (824772519e8b9ac65e01.js:117)
    at _a (824772519e8b9ac65e01.js:117)
    at Immediate._onImmediate (824772519e8b9ac65e01.js:45)
    at runCallback (timers.js:694)
    at tryOnImmediate (timers.js:665)
    at processImmediate (timers.js:647)

**Comment by aeder** [comment] 2019-02-14 02:38
I have the same issue. Also if I run Discord from console I get the following output:

`[aeder@ryzen-pc ~]$ flatpak run com.discordapp.Discord 
Discord 0.0.8
Starting updater.
[Modules] Modules initializing
[Modules] Distribution: remote
[Modules] Host updates: enabled
[Modules] Module updates: enabled
[Modules] Module install path: /home/aeder/.var/app/com.discordapp.Discord/config/discord/0.0.8/modules
[Modules] Module installed file path: /home/aeder/.var/app/com.discordapp.Discord/config/discord/0.0.8/modules/installed.json
[Modules] Module download path: /home/aeder/.var/app/com.discordapp.Discord/config/discord/0.0.8/modules/pending
[Modules] No updates to install
[Modules] Checking for host updates.
[Modules] Host is up to date.
[Modules] Checking for module updates at https://discordapp.com/api/modules/stable/versions.json
[Modules] No module updates available.
[Modules] Starting to install discord_media...
[Modules] Fetching discord_media@0 from https://discordapp.com/api/modules/stable/discord_media/0
[Modules] Streaming discord_media@0 [251 bytes] to /home/aeder/.var/app/com.discordapp.Discord/config/discord/0.0.8/modules/pending/discord_media-0.zip
[Modules] Finished module downloads. [success: 0] [failure: 1]
`

**Comment by aeder** [comment] 2019-02-14 02:46
Also the workaround described in this comment makes it work for me: https://github.com/flathub/com.discordapp.Discord/issues/48#issuecomment-456210527

So it might be this is just a duplicate of that issue.

**Comment by Cxpher** [comment] 2019-02-14 05:47
Hi all,

I stopped using the flatpak. Copy in AUR works perfectly so I use that now.

This is an issue specifically with the flatpak.

**Comment by amz-x** [comment] 2019-05-26 18:12
Same issue here.

Fedora 30
Flatpak 1.2.4
Discord 0.9

Adding TZ environment variable to run command helped me.
```
flatpak run --env=TZ=America/New_York com.discordapp.Discord
```

**Comment by kurobeats** [comment] 2019-06-24 21:15
> Same issue here.
> 
> Fedora 30
> Flatpak 1.2.4
> Discord 0.9
> 
> Adding TZ environment variable to run command helped me.
> 
> ```
> flatpak run --env=TZ=America/New_York com.discordapp.Discord
> ```

This workaround works for me too.

**Comment by laywah2016** [comment] 2019-07-03 08:58
I am also having issues but running
`flatpak run --env=TZ=America/New_York com.discordapp.Discord` fixed this for me too.

**Comment by kassindornelles** [comment] 2019-08-05 02:45
there's anyone maintaining the discord flatpak?
 that bug still exist.

**Comment by arifur** [comment] 2019-09-21 09:35
I am also facing crashes.

**Comment by arifur** [comment] 2019-09-21 09:36
Flatpak Discord still crashing

**Comment by iglosiggio** [comment] 2019-10-04 03:55
Hi (im going to repost this in all the duplicated issues). After digging a while seems caused by [this](https://bugs.chromium.org/p/chromium/issues/detail?id=364374) bug in chromium. Maybe updating the electron version will fix it?

**Comment by eiglow** [comment] 2020-10-22 08:00
I think this issue has been fixed, I can no longer reproduce it.

**Closed** 2020-10-22 12:19 UTC
