### ISSUE TITLE
Discord 0.0.40 Flatpak fails to launch on PopOS 22.04 LTS

### ISSUE THREAD

**Issue by CloudCassette** [flathub/com.discordapp.Discord#361] opened 2024-01-11 23:29 UTC
After updating the Flatpak to 0.0.40 Discord fails to launch. 
Lenovo ThinkPad T490
10th Gen i5-10210U CPU 1.60GHz x 8
Mesa Intel UHD Graphics
16GB memory
PopOS 22.04 LTS
GNOME version 42.9
X11

Output for `flatpak run com.discordapp.Discord`

```
💁  cloudcassette @ 💻  pop-os in 📁  ~
└❯ flatpak run com.discordapp.Discord
Disabling updates already done
Discord 0.0.40
Gtk-Message: 18:20:02.995: Failed to load module "canberra-gtk-module"
Gtk-Message: 18:20:02.996: Failed to load module "canberra-gtk-module"
[5:0111/182003.015105:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[5:0111/182003.015140:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Starting app.
Starting updater.
2024-01-11T23:20:03.046Z [Modules] Modules initializing
2024-01-11T23:20:03.047Z [Modules] Distribution: remote
2024-01-11T23:20:03.047Z [Modules] Host updates: disabled
2024-01-11T23:20:03.047Z [Modules] Module updates: enabled
2024-01-11T23:20:03.048Z [Modules] Module install path: /home/cloudcassette/.var/app/com.discordapp.Discord/config/discord/0.0.40/modules
2024-01-11T23:20:03.048Z [Modules] Module installed file path: /home/cloudcassette/.var/app/com.discordapp.Discord/config/discord/0.0.40/modules/installed.json
2024-01-11T23:20:03.048Z [Modules] Module download path: /home/cloudcassette/.var/app/com.discordapp.Discord/config/discord/0.0.40/modules/pending
splashScreen.initSplash(false)
blackbox: 2024-01-11T23:20:03.070Z 0

----------------------------------------------
blackbox: 2024-01-11T23:20:03.099Z 1 Discord starting: {"releaseChannel":"stable","version":"0.0.40"}, modulepath: /home/cloudcassette/.var/app/com.discordapp.Discord/config/discord/0.0.40/modules
blackbox: 2024-01-11T23:20:03.107Z 2 ✅ webContents.created web1 ""
blackbox: 2024-01-11T23:20:03.114Z 3 ✅ window.created win1 "discord"
splashScreen: SPLASH_SCREEN_READY
splashScreen.webContentsSend: SPLASH_SCREEN_QUOTE SPLASH_SCREEN_QUOTE [ 'Hold Tight — Loading Discord' ]
2024-01-11T23:20:03.218Z [Modules] No updates to install
splashScreen: no-pending-updates
2024-01-11T23:20:03.219Z [Modules] Host is up to date.
2024-01-11T23:20:03.219Z [Modules] Checking for module updates at https://discord.com/api/modules/stable/versions.json
splashScreen: checking-for-updates
splashScreen.updateSplashState checking-for-updates checking-for-updates {}
splashScreen.webContentsSend: SPLASH_UPDATE_STATE SPLASH_UPDATE_STATE [ { status: 'checking-for-updates' } ]
[56:0111/182003.267191:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
[56:0111/182003.267340:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
[56:0111/182003.268291:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
[56:0111/182003.269603:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
[56:0111/182003.271548:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
blackbox: 2024-01-11T23:20:03.272Z 4 ✅ webContents.did-finish-load web1
[56:0111/182003.314701:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
[56:0111/182003.314825:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
[56:0111/182003.315493:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
2024-01-11T23:20:03.469Z [Modules] No module updates available.
splashScreen: update-check-finished true 0 false
splashScreen.launchMainWindow: false
Optional module ./ElectronTestRpc was not included.
splashScreen.updateSplashState launching launching {}
splashScreen.webContentsSend: SPLASH_UPDATE_STATE SPLASH_UPDATE_STATE [ { status: 'launching' } ]
[5:0111/182003.559492:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[5:0111/182003.559536:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[5:0111/182003.559566:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
blackbox: 2024-01-11T23:20:03.559Z 5 ✅ webContents.created web2 ""
[56:0111/182003.563557:ERROR:skia_output_surface_impl.cc(948)]
  surface_size=65520x65459
  format=4
  color_type=4
  backend_format.isValid()=1
  backend_format.backend()=0
  backend_format.asGLFormat()=1
  backend_format.asVkFormat()=0
  backend_format.asVkFormat() vk_format=0
  sample_count=1
  surface_origin=1
  willGlFBO0=1
[56:0111/182003.564443:ERROR:skia_output_device_gl.cc(275)] Couldn't create surface:
  abandoned()=0
  color_type=0
  framebuffer_info.fFBOID=0
  framebuffer_info.fFormat=0
  color_space={r:[0.6531, 0.3360], g:[0.3233, 0.6131], b:[0.1513, 0.3360], w:[0.3127, 0.3290]}, transfer:SRGB, matrix:RGB, range:FULL}
  size=0x0
[56:0111/182003.564584:ERROR:gpu_service_impl.cc(988)] Exiting GPU process because some drivers can't recover from errors. GPU process will restart shortly.
[5:0111/182003.572316:ERROR:gpu_process_host.cc(991)] GPU process exited unexpectedly: exit_code=8704
(electron) 'gpu-process-crashed event' is deprecated and will be removed. Please use 'child-process-gone event' instead.
notificationScreen.webContentsSend: win is invalid undefined.
child-process-gone! child: GPU (undefined) exitCode: 8704
blackbox: 2024-01-11T23:20:03.586Z 6 ✅ window.created win2 "Discord"
2024/01/11 18:20:03 socat[3] W exiting on signal 15
```

I tried removing it and re-installing it but get the same error.

**Comment by ZVNexus** [comment] 2024-01-18 00:22
@CloudCassette Can you try out this build?
flatpak install --user https://dl.flathub.org/build-repo/76860/com.discordapp.Discord.flatpakref

**Comment by CloudCassette** [comment] 2024-01-18 23:51
> @CloudCassette Can you try out this build? flatpak install --user https://dl.flathub.org/build-repo/76860/com.discordapp.Discord.flatpakref

This fixed the issue for me thank you

**Comment by CloudCassette** [comment] 2024-01-18 23:58
> @CloudCassette Can you try out this build? flatpak install --user https://dl.flathub.org/build-repo/76860/com.discordapp.Discord.flatpakref

At first I thought this fixed my issue, but I had installed the deb package because I couldn't take not being able to use Discord. So at first I thought it worked but after I removed the deb package I was getting the same behavior.

```
┌💁  cloudcassette @ 💻  pop-os in 📁  ~
└❯ flatpak run com.discordapp.Discord
Disabling updates already done
Discord 0.0.40
Gtk-Message: 18:55:14.398: Failed to load module "canberra-gtk-module"
Gtk-Message: 18:55:14.399: Failed to load module "canberra-gtk-module"
[5:0118/185514.418532:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[5:0118/185514.418613:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Starting app.
Starting updater.
2024-01-18T23:55:14.446Z [Modules] Modules initializing
2024-01-18T23:55:14.447Z [Modules] Distribution: remote
2024-01-18T23:55:14.447Z [Modules] Host updates: disabled
2024-01-18T23:55:14.447Z [Modules] Module updates: enabled
2024-01-18T23:55:14.447Z [Modules] Module install path: /home/cloudcassette/.var/app/com.discordapp.Discord/config/discord/0.0.40/modules
2024-01-18T23:55:14.447Z [Modules] Module installed file path: /home/cloudcassette/.var/app/com.discordapp.Discord/config/discord/0.0.40/modules/installed.json
2024-01-18T23:55:14.447Z [Modules] Module download path: /home/cloudcassette/.var/app/com.discordapp.Discord/config/discord/0.0.40/modules/pending
splashScreen.initSplash(false)
blackbox: 2024-01-18T23:55:14.468Z 0

----------------------------------------------
blackbox: 2024-01-18T23:55:14.499Z 1 Discord starting: {"releaseChannel":"stable","version":"0.0.40"}, modulepath: /home/cloudcassette/.var/app/com.discordapp.Discord/config/discord/0.0.40/modules
blackbox: 2024-01-18T23:55:14.507Z 2 ✅ webContents.created web1 "index.html"
blackbox: 2024-01-18T23:55:14.514Z 3 ✅ window.created win1 "discord"
splashScreen: SPLASH_SCREEN_READY
splashScreen.webContentsSend: SPLASH_SCREEN_QUOTE SPLASH_SCREEN_QUOTE [ 'Hold Tight — Loading Discord' ]
2024-01-18T23:55:14.612Z [Modules] No updates to install
splashScreen: no-pending-updates
2024-01-18T23:55:14.612Z [Modules] Host is up to date.
2024-01-18T23:55:14.613Z [Modules] Checking for module updates at https://discord.com/api/modules/stable/versions.json
splashScreen: checking-for-updates
splashScreen.updateSplashState checking-for-updates checking-for-updates {}
splashScreen.webContentsSend: SPLASH_UPDATE_STATE SPLASH_UPDATE_STATE [ { status: 'checking-for-updates' } ]
[56:0118/185514.668990:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
[56:0118/185514.669106:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
[56:0118/185514.669189:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
[56:0118/185514.670772:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
[56:0118/185514.672609:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
blackbox: 2024-01-18T23:55:14.672Z 4 ✅ webContents.did-finish-load web1
[56:0118/185514.706607:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
2024-01-18T23:55:14.808Z [Modules] No module updates available.
splashScreen: update-check-finished true 0 false
splashScreen.launchMainWindow: false
Optional module ./ElectronTestRpc was not included.
splashScreen.updateSplashState launching launching {}
splashScreen.webContentsSend: SPLASH_UPDATE_STATE SPLASH_UPDATE_STATE [ { status: 'launching' } ]
[5:0118/185514.922269:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[5:0118/185514.922329:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[5:0118/185514.922364:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
blackbox: 2024-01-18T23:55:14.922Z 5 ✅ webContents.created web2 ""
[56:0118/185514.925844:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
[56:0118/185514.927764:ERROR:skia_output_surface_impl.cc(948)]
  surface_size=65520x65459
  format=4
  color_type=4
  backend_format.isValid()=1
  backend_format.backend()=0
  backend_format.asGLFormat()=1
  backend_format.asVkFormat()=0
  backend_format.asVkFormat() vk_format=0
  sample_count=1
  surface_origin=1
  willGlFBO0=1
[56:0118/185514.928586:ERROR:skia_output_device_gl.cc(275)] Couldn't create surface:
  abandoned()=0
  color_type=0
  framebuffer_info.fFBOID=0
  framebuffer_info.fFormat=0
  color_space={r:[0.6531, 0.3360], g:[0.3233, 0.6131], b:[0.1513, 0.3360], w:[0.3127, 0.3290]}, transfer:SRGB, matrix:RGB, range:FULL}
  size=0x0
[56:0118/185514.928768:ERROR:gpu_service_impl.cc(988)] Exiting GPU process because some drivers can't recover from errors. GPU process will restart shortly.
[5:0118/185514.936389:ERROR:gpu_process_host.cc(991)] GPU process exited unexpectedly: exit_code=8704
(electron) 'gpu-process-crashed event' is deprecated and will be removed. Please use 'child-process-gone event' instead.
notificationScreen.webContentsSend: win is invalid undefined.
child-process-gone! child: GPU (undefined) exitCode: 8704
blackbox: 2024-01-18T23:55:14.952Z 6 ✅ window.created win2 "Discord"
blackbox: 2024-01-18T23:55:14.975Z 7 before-quit
2024/01/18 18:55:15 socat[3] W exiting on signal 15
```

**Comment by avatar382** [comment] 2024-01-31 18:18
> @CloudCassette Can you try out this build? flatpak install --user https://dl.flathub.org/build-repo/76860/com.discordapp.Discord.flatpakref

I'm having the same problem, but the link above 404s for me.

Is there another release I can try?

**Comment by TingPing** [comment] 2024-01-31 19:44
> Having the same issues with the snap and deb releases.

You just have some broken DNS configuration. Maybe a weird dns tool touches `/etc/resolv.conf`.

**Comment by guihkx** [comment] 2024-10-03 03:00
```
[56:0111/182003.267191:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: BGRA_8888, share_between_threads: 0, gmb_type: shared_memory
```

That error indicates this is a duplicate of #307.

**Closed by guihkx** 2024-10-03 03:00 UTC
