### ISSUE TITLE
Notifications on Ubuntu Dock are not working

### ISSUE THREAD

**Issue by tosziro** [flathub/com.discordapp.Discord#124] opened 2020-12-07 18:27 UTC
Notifications on Ubuntu Dock are not working on Flathub version. They work fine on .deb version. 

There should be indicator with number of unread messages like below. (.deb version screen)
![obraz](https://user-images.githubusercontent.com/41963712/101389752-2c1f6d00-38c2-11eb-99fc-1e1bef5c8bc9.png)

**Comment by Fuseteam** [comment] 2020-12-08 00:28
an uneducated guess would be that it is related to libindicator
a quick way to test would be to test the snap version

**Comment by tosziro** [comment] 2020-12-09 07:38
> an uneducated guess would be that it is related to libindicator
> a quick way to test would be to test the snap version

Same problem on snap version. Only .deb one works correct.

**Comment by Fuseteam** [comment] 2020-12-10 02:24
Well there goes that theory

**Comment by TingPing** [comment] 2020-12-10 03:43
Probably need to build the indicator library and add the permission for it.

**Comment by lionirdeadman** [comment] 2021-01-08 01:01
Uhhhh, can you still use this? I just tried reproducing this in a fresh Ubuntu VM and it didn't work? @tosziro

**Comment by lionirdeadman** [comment] 2021-01-09 04:14
I've managed to reproduce it once and thought I got it but I can't figure out why it won't work. It should've worked with the changes in #132 but it doesn't.

If someone wants to point a discord dev or try to debugging this, feel free. I'm personally giving up on it for now.

**Comment by lionirdeadman** [comment] 2021-01-13 20:21
Oops.

**Comment by guihkx** [comment] 2024-10-02 17:33
Can some Ubuntu user please revisit this bug report?

**Comment by guihkx** [comment] 2024-10-05 03:30
After testing this myself, I can say this now works for me™:

My test was done with Discord 0.0.70, running on a Ubuntu 20.04 virtual machine, on Wayland:

![Screenshot from 2024-10-05 03-26-05](https://github.com/user-attachments/assets/2abd9df0-40a4-4864-aa1e-2a1ff9230093)

Closing as completed.

**Closed by guihkx** 2024-10-05 03:30 UTC
Labels: enhancement, help wanted
