### ISSUE TITLE
Unable to upload files on Linux using Flatpak

### ISSUE THREAD

**Issue by evilphish** [flathub/com.discordapp.Discord#448] opened 2024-09-28 11:19 UTC
Getting a very descriptive error message here
![image](https://github.com/user-attachments/assets/bad0a46f-b2cc-475b-9745-4da3e5e974e7)

The general problem seems to be similar to or even the same as this report: https://github.com/flathub/com.discordapp.Discord/issues/237

Using flatpak discord in Linux Mint 22 Cinnamon. All necessary permission like home access have been granted. I can see the thumbnail in the message preview correctly but upon hitting send I get the error "Something went wrong".

**Comment by guihkx** [comment] 2024-09-28 13:36
I cannot reproduce the issue here:

https://github.com/user-attachments/assets/8d7a98c9-a53f-4884-bb4b-74839bb6e86c

**Comment by evilphish** [comment] 2024-09-28 16:43
Are you using Flatpak or direct install?

**Comment by guihkx** [comment] 2024-09-28 18:50
Flatpak, of course.

**Comment by guihkx** [comment] 2024-09-28 20:48
Does drag and drop work if you get a file from the ~/Downloads folder?

**Comment by evilphish** [comment] 2024-09-29 11:47
No. It actually does not matter whether I drag & drop or select "+" and then navigate through the file open dialog. If I select a file from a folder where Discord has permission (e.g., Downloads , Pictures, Video) then the file gets added to the message draft and I can see the thumbnail. Which kind of tells me that discord can find the file because if I drag & drop a file from a different location the thumbnail is missing (as it should be as discord does not have access there). 

So while drafting the message and using the correct folders everything works fine but as soon as I hit send I get the "Something went wrong" error.

**Comment by guihkx** [comment] 2024-09-30 12:18
Thanks for investigating it further. So I assume we can close this, given it's not an issue with Flatpak.

**Closed by guihkx** 2024-09-30 12:18 UTC
Labels: cannot reproduce
